import React from "react";
import Header from "../../components/header/header";
import Footer from "../../components/footer/footer";

const TermsAndConditions = () => {
    return (
        <React.Fragment>
            <div>
                <Header />
            </div>
            <section className="about pt-4 pt-lg-5">
                <div className="container">
                    <h1 className="title text-center">Terms and Conditions</h1>
                </div>
            </section>
            <section className="pt-1 pt-lg-2">
                <header style={{
                                    position: "relative",
                                    zIndex: 1,
                                    padding: "30px 50px",
                                    backgroundColor: "#eeeded",
                                    color: "rgb(92, 90, 90)",
                                 }}>
                    <div className="">
                        <h2 className="h5 title">CONTRACTUAL RELATIONSHIPs</h2>
                        <div className="text "  >
                            <p>Service Easy Technology Private Limited, incorporated under the Companies Act, 2013, having its registered office at F-212, DLF NEW TOWN HEIGHTS, SECTOR 91, Garhi Harsaru, Gurugram, Haryana – 122505, operating under the trademarked name “GoMechanic”, provides holistic car services including maintenance, repair, etc. The use and access of our website www.gomechanic.in (“Website”), and our mobile applications “GoMechanic - Car Services, Battery & Tyre” (“Applications”), or any products or services in connection with the Application or Website (“Services”) shall be governed by these terms and conditions (“Terms”). The Website and Applications are together called the “Platform”.

                                These terms constitute a legally binding and enforceable agreement between GoMechanic (“Company/we/us/our”) and its Users (“User/you/your”) and govern your use of the Platform to browse and/or avail the Services displayed by us on the Platform. By accessing and using our Services, you agree to be bound by these terms, establishing a contractual relationship between you and the Company. In case you do not agree to the terms, you may not use or access or stop your use or access of our Services. These Terms expressly supersede prior written agreements with you. The Company requests the User to carefully go through these terms & conditions (“Terms and Conditions” or “Terms”) prior to accessing the Platform or availing Services (as defined below) using the Platform.

                                The Company reserves the right, in its sole discretion, to change, modify or amend the Terms for complying with the legal or regulatory framework and for other legitimate business purposes, at any time, and the Company will post the amended Terms at the domain of www.gomechanic.in/terms. It is your responsibility to review the Terms for any changes and you are encouraged to check the Terms frequently. The Company shall not be under an obligation to notify Users of any changes to the Terms and Conditions. If you continue to use the Platform, Content (as defined below) and/or Services after the updated Terms and Conditions have been published, it shall be deemed that you have read and understood and accept the updated Terms and Conditions. Any reference to Terms and Conditions, made herein shall refer to the latest version of the Terms and Conditions.

                                No information provided on the Platform shall be considered a substitute for your independent investigation. These Terms are collectively an electronic record in terms of the Indian Contract Act, 1872; the Information Technology Act, 2000, the rules made thereunder; and the amended provisions pertaining to the electronic records in various other statutes as amended by the Information Technology Act, 2000. These Terms are generated by a computer system and do not require any digital or electronic signature.</p>
                        </div>
                    </div>
                    <div className="container">
                        <h2 className="h5 title">DEFINITIONS</h2>
                        <div className="text">
                            <p>“Content” will include (but is not limited to) reviews, images, photos, audio, video, location data, nearby places, and all other forms of information or data. "Your Content" or "User Content" means Content that you upload, share or transmit, through or in connection with the Services, such as likes, ratings, reviews, images, photos, messages, profile information, and any other materials that you publicly display or displayed in your account profile. "GoMechanic Content" means Content that the Company creates and makes available in connection with the Services including, but not limited to, visual interfaces, interactive features, graphics, design, compilation, computer code, products, software, aggregate ratings, reports and other usage-related data in connection with activities associated with your account and all other elements and components of the Services excluding Your Content.

                                “Estimated Cost” will include the service provider’s approximation of what the Service is likely to cost. The purpose of cost estimation is to predict the quantity, cost, and price of the resources required to complete a job.

                                “Membership Plan(s)” means subscription or other kinds of membership offers provided by the Company to Users from time to time through online or offline media. The terms, conditions and prices of such plans shall be communicated through the applicable media at the time of issuance of such offers.

                                “Service(s)” means services provided through the Platform, as described in further detail under Clause 3 below. The Services provided through the Platform may change from time to time, at the sole discretion of the Company.

                                “User” or “You” shall mean any individual who owns a car (primarily out of the manufacture warranty period) in urban centers especially metros, who is desirous of availing Services on the Platform as and who are registered on the Platform for this purpose.</p>
                        </div>
                    </div>
                    <div className="container">
                        <h2 className="h5 titlee">SERVICES</h2>
                        <div className="text">
                            <p>The Services constitute a technology platform that enables Users of the Company’s Platform, provided as part of the Services, to arrange and schedule repair or maintenance services for your car with independent third-party providers. Once you submit a request, we may provide you with a list of possible service providers along with their experience information.

                                The Company also provides towing service to get your vehicle out of the situation and back on road on a chargeable basis.

                                You acknowledge that the Company does not provide any repair and maintenance services for its customers and that all such above stated services are provided by other independent third-party contractors who are not employed by the Company.

                                You acknowledge that even after accepting and/or confirming an appointment for service/repair of your car, the Company cannot guarantee its availability. At the time of your appointment request to the Company, the Company will make reasonable efforts to connect you with the independent third-party service provider so that you can avail automobile repair service at or near your location.

                                You acknowledge that the cost and time period for the services/repairs are estimated in accordance with your request and are proximate in nature.</p>
                        </div>
                    </div>
                    <div className="container">
                        <h2 className="h5 title">SERVICES</h2>
                        <div className="text">
                            <p>The Services constitute a technology platform that enables Users of the Company’s Platform, provided as part of the Services, to arrange and schedule repair or maintenance services for your car with independent third-party providers. Once you submit a request, we may provide you with a list of possible service providers along with their experience information.

                                The Company also provides towing service to get your vehicle out of the situation and back on road on a chargeable basis.

                                You acknowledge that the Company does not provide any repair and maintenance services for its customers and that all such above stated services are provided by other independent third-party contractors who are not employed by the Company.

                                You acknowledge that even after accepting and/or confirming an appointment for service/repair of your car, the Company cannot guarantee its availability. At the time of your appointment request to the Company, the Company will make reasonable efforts to connect you with the independent third-party service provider so that you can avail automobile repair service at or near your location.

                                You acknowledge that the cost and time period for the services/repairs are estimated in accordance with your request and are proximate in nature.</p>
                        </div>
                    </div>
                    <div className="container">
                        <h2 className="h5 title">ELIGIBILITY</h2>
                        <div className="text">
                            <p>You hereby represent and warrant that you are eighteen (18) years of age or above and are fully able and competent to understand and agree to the terms, conditions, obligations, affirmations, representations, and warranties set forth in these terms, and to abide by and comply with the Terms stated therein.

                                You are in compliance with all laws and regulations in the country in which you live when you access and use the Services. You agree to use the Services only in compliance with these Terms and applicable laws, and in a manner that does not violate our legal rights or those of any third-parties.

                                If you will be using the Services on behalf of an organization, you agree to these Terms on behalf of that organization and you represent that you have the authority to act on behalf of your organization.</p>
                        </div>
                    </div>
                    <div className="container">
                        <h2 className="h5 titlee">USE OF SERVICES</h2>
                        <div className="text">
                            <p>You must create an account in order to use some of the features offered by the Platform. Use of any personal information you provide to us during the account creation process is governed by our Privacy Policy available on our app/website. You must keep your password confidential and you are solely responsible for maintaining the confidentiality and security of your account details, all changes and updates submitted through your account, and all activities that occur in connection with your account.

                                Following sign-up, we will make certain Services available to you free of charge. The Services will include the ability to search for service providers for automotive repair or servicing work, the ability to view detailed profiles of service providers and their service prices and rating information, and the ability to post feedback and ratings in relation to any service provider you have used as a result of your use of the Platform. We reserve the right to add, change or remove Services from our Platform at any time, and may make certain Services chargeable at our discretion.

                                You must only book a Service if you have </p>
                        </div>
                    </div>
                    <div className="container">
                        <h2 className="h5 title">SUPPORTS</h2>
                        <div className="text">
                            <p>The Company offers an email as well as phone call based support system along with an online knowledge pool of FAQs. In case you require any assistance or support, you may access support resources or contact our support by emailing at info@gomechanic.in or calling our helpline at +91-8398970970 (Monday to Sunday between 7 am and 9 pm).

                                The Company shall revert to every complaint at the earliest upon receipt of the complaint during the business days. Further, the Company shall take the best possible efforts to redress the complaint within 7 days of receipt of the complaint. Any suggestions by the Company regarding the use of the Services shall not be construed as a warranty.

                                The User agrees and acknowledges that the Company shall address and attempt to resolve the complaint received in accordance with the standard policies and procedures adopted by the Company, the User’s disapproval/discontent with the outcome/mode of redressal shall not be deemed to mean non-redressal of the complaint by the Company. Any suggestions by the Company regarding the use of the Service shall not be construed as a warranty.

                                The Company shall take reasonable care and measures required for the safety of your car in our possession. In the event, the User’s car is stolen while in the possession of the Company, the Company will take all reasonable measures and extend necessary support to the User for recovering their </p>
                        </div>
                    </div>
                </header>
            </section>
            <div>
                <Footer />
            </div>
        </React.Fragment>
    );
};

export default TermsAndConditions;
